version: '3'
services:
  trino:
    image: trinodb/trino:latest
    ports:
      - "8080:8080"
    volumes:
      - ./trino/etc:/etc/trino
    networks:
      - trino-network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres-init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - trino-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo-init.js:/docker-entrypoint-initdb.d/init.js
    networks:
      - trino-network

networks:
  trino-network: